---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: IRSA
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
 name: xpostgresqlinstances.database.rds.example.org
spec:
 claimNames:
   kind: PostgreSQLInstance
   plural: postgresqlinstances
 connectionSecretKeys:
 - type
 - provider
 - host
 - port
 - database
 - username
 - password
 group: database.rds.example.org
 names:
   kind: XPostgreSQLInstance
   plural: xpostgresqlinstances
 versions:
 - name: v1alpha1
   referenceable: true
   schema:
     openAPIV3Schema:
       properties:
         spec:
          properties:
            storageGB:
              type: integer
              default: 20
          type: object
       type: object
   served: true

---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
 labels:
   provider: "aws"
   vpc: "default"
 name: xpostgresqlinstances.database.rds.example.org
spec:
 compositeTypeRef:
   apiVersion: database.rds.example.org/v1alpha1
   kind: XPostgreSQLInstance
 publishConnectionDetailsWithStoreConfigRef:
   name: default
 resources:
 - name: subnet-group
   base: 
     apiVersion: rds.aws.upbound.io/v1beta1
     kind: SubnetGroup
     metadata:
       name: tap-run-prod-subnet-group
     spec:
       forProvider:
         region: us-west-2
         description: "run-prod subnet group"
         subnetIds:
           - subnet-09890d9754ea57db9
           - subnet-0fe9c0e02e17bb03a     
           - subnet-0d94164b8ff3b634d
           - subnet-0bb4fa64cf6b90af6
           - subnet-0eb78fe364fc99b1c
           - subnet-0885bd28d88a3db9e
         tags:
           charge: tap-run-prod
       providerConfigRef:
         name: default
 - name: rds-instance
   base:
     apiVersion: rds.aws.upbound.io/v1beta1
     kind: Instance
     metadata:
       annotations:
         meta.upbound.io/example-id: rds/v1beta1/instance
       labels:
         testing.upbound.io/example-name: example-dbinstance
       name: example-dbinstance-${Rand.RFC1123Subdomain}
     spec:
       forProvider:
         allocatedStorage: 20
         autoGeneratePassword: true
         autoMinorVersionUpgrade: true
         backupRetentionPeriod: 14
         engine: postgres
         engineVersion: "13.7"
         instanceClass: db.t3.micro
         name: postgres
         passwordSecretRef:
           key: password
           name: example-dbinstance
           namespace: crossplane-system
         publiclyAccessible: false
         region: us-west-2
         skipFinalSnapshot: true
         storageEncrypted: true
         storageType: gp2
         username: adminuser
         dbSubnetGroupName: tap-run-prod-subnet-group
         vpcSecurityGroupIds: 
         - sg-06243512b6cfb8d6d
       writeConnectionSecretToRef:
         namespace: crossplane-system
   connectionDetails:
   - name: type
     value: postgresql
   - name: provider
     value: aws
   - name: database
     value: postgres
   - fromConnectionSecretKey: username
   - fromConnectionSecretKey: password
   - name: host
     fromConnectionSecretKey: endpoint
   - fromConnectionSecretKey: port
   name: rdsinstance
   patches:
   - fromFieldPath: metadata.uid
     toFieldPath: spec.writeConnectionSecretToRef.name
     transforms:
     - string:
         fmt: '%s-postgresql'
         type: Format
       type: string
     type: FromCompositeFieldPath
   - fromFieldPath: spec.storageGB
     toFieldPath: spec.forProvider.allocatedStorage
     type: FromCompositeFieldPath